use std::error::Error;

pub fn do_assignment_7() -> Result<(), Box<dyn Error>> {
    Ok(())
}
